setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck
getExchangeRates:
    path: /api/exchange-rates
    controller: App\Controller\ExchangeRatesController::getExchangeRates

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

