# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.nbp_api_url: '%env(APP_NBP_API_URL)%'
    app.exchange_rates_route: '%env(APP_EXCHANGE_RATES_ROUTE)%'
    app.currency_config: '%kernel.project_dir%/config/currency_config.yaml'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        autowire: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\NbpExchangeRatesService:
        arguments:
            $currencyConfig: '%app.currency_config%'

    App\Service\NbpClientService:
        arguments:
            $nbpApiUrl: '%app.nbp_api_url%'
            $nbpExchangeRatesRoute: '%app.exchange_rates_route%'
